using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WWAchvBot_3
{
    public static class Names
    {
        public static List<string> Roles = new List<string>()
        {
            "AlphaWolf",
            "ApprenticeSeer",
            "Beholder",
            "Blacksmith",
            "Cupid",
            "ClumsyGuy",
            "Cultist",
            "CultistHunter",
            "Cursed",
            "Detective",
            "Doppelgänger",
            "Drunk",
            "Fool",
            "Guardian Angel",
            "Gunner",
            "Harlot",
            "Hunter",
            "Mason",
            "Mayor",
            "Prince",
            "Seer",
            "SerialKiller",
            "Sorcerer",
            "Tanner",
            "Traitor",
            "Villager",
            "Werewolf",
            "WildChild",
            "WolfCub",
            "SeerFool",
            "Unknown",
        };

        public static List<string> Achievements = new List<string>()
        {
            "Welcome to Hell",
            "Welcome to the Asylum",
            "Alzheimer's Patient",
            "O HAI DER!",
            "Spy vs Spy",
            "I Have No Idea What I'm Doing",
            "Enochlophobia",
            "Introvert",
            "Naughty!",
            "Dedicated",
            "Obsessed",
            "Masochist",
            "Wobble Wobble",
            "Inconspicuous",
            "Survivalist",
            "Promiscuous",
            "Mason Brother",
            "Double Shifter",
            "Hey Man, Nice Shot",
            "That's Why You Don't Stay Home",
            "Double Vision",
            "Double Kill",
            "Should Have Known",
            "I See a Lack of Trust",
            "Sunday Bloody Sunday",
            "Change Sides Works",
            "Forbidden Love",
            "Developer",
            "The First Stone",
            "Smart Gunner",
            "Streetwise",
            "Speed Dating",
            "Even a Stopped Clock is Right Twice a Day",
            "So Close!",
            "Cultist Convention",
            "Self Loving",
            "Should've Said Something",
            "Tanner Overkill",
            "Cultist Fodder",
            "Lone Wolf",
            "Pack Hunter",
            "Saved by the Bull(et)",
            "In for the Long Haul",
            "OH SHI-",
            "Veteran",
            "No Sorcery!",
            "Cultist Tracker",
            "I'M NOT DRUN-*BURPPP*",
            "Did you guard yourself?",
            "Spoiled Rich Brat",
            "President",
            "I Helped!",
            "It Was a Busy Night!",
            "Serial Samaritan",
            "Wuffie-Cult",
            "Three Little Wolves and a Big Bad Pig",
            "Here's Johnny",
            "I've Got Your Back",
            "Explorer",
            "Linguist",
            "Black Sheep",
        };
    }
}
